# Generated by Django 4.2.5 on 2023-10-31 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LibraLoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('book_id', models.CharField(max_length=100)),
                ('book_image', models.ImageField(blank=True, upload_to='book_images/')),
                ('book_download_link', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
                ('ISBN', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('book_status', models.CharField(max_length=100)),
                ('book_rating', models.CharField(max_length=100)),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_pages', models.CharField(max_length=100)),
                ('book_language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category_image', models.ImageField(blank=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('member_image', models.ImageField(blank=True, upload_to='member_images/')),
                ('member_id', models.CharField(max_length=100)),
                ('member_status', models.CharField(max_length=100)),
                ('member_type', models.CharField(max_length=100)),
                ('member_dob', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('reservation_id', models.CharField(max_length=100)),
                ('reservation_type', models.CharField(max_length=100)),
                ('reservation_status', models.CharField(max_length=100)),
                ('reservation_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraLoom.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraLoom.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraLoom.category'),
        ),
    ]
