# Generated by Django 4.2.5 on 2023-11-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraLoom', '0003_remove_reservation_reservation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraLoom.category', to_field='name'),
        ),
    ]
