# Generated by Django 4.2.5 on 2023-11-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraLoom', '0004_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_download_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
