# Generated by Django 4.2.5 on 2023-11-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraLoom', '0005_alter_book_book_download_link_alter_book_book_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_status',
        ),
        migrations.AddField(
            model_name='book',
            name='book_Availability',
            field=models.BooleanField(default=True),
        ),
    ]
