# Generated by Django 4.2.5 on 2023-11-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraLoom', '0008_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
